version: 1
transform:
  default:
    writeStrategy:
      type: APPEND
  tasks:
    - name: byseller_kpi
      parseSQL: false
      sink:
        partition:
          - timestamp
    - name: byseller_kpi0
      table: byseller_kpi
      sink:
        partition:
          - timestamp

