application:
  accessPolicies:
    apply: true
    location: EU
    taxonomy: RGPD

  connections:
    bigquery:
      type: "bigquery"
      options:
        gcsBucket: "starlake-app"
        authType: "APPLICATION_DEFAULT"
        authScopes: "https://www.googleapis.com/auth/cloud-platform" # comma separated list of scopes
        #authType: SERVICE_ACCOUNT_JSON_KEYFILE
        #jsonKeyfile: "/Users/hayssams/.gcloud/keys/starlake-hayssams.json"

    localFilesystem:
      type: "fs"

  spark:
    delta:
      logStore:
        class: org.apache.spark.sql.delta.storage.LocalLogStore
    datasource:
      bigquery:
        materializationDataset: "BQ_TEST_DS"


  connectionRef: "{{ myConnectionRef }}"
