language: scala
jdk:
  #- oraclejdk8
  #- oraclejdk9
  - openjdk8
  - openjdk11
  # Note: as of 2020-02-11, JDK11 doesn't work (ASM6 can't support bytecode version 55)

scala:
  - 2.11.12
  - 2.12.10


script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)


