os: linux 
  
dist: bionic
language: scala
jdk:
  - openjdk8
  - openjdk11

scala:
  - 2.12.12

env:
  - COMET_SPARK_VERSION=2.4.7
  - COMET_SPARK_VERSION=3.0.1

jobs:
  allow_failures:
    # we test, but since support of jdk>8 by spark 2.4.7 isn't official, it's okay to fail
    - jdk: openjdk11
      env: COMET_SPARK_VERSION=2.4.7
      
    
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)


