---
application:
  loader: "native" # "spark" (default) or "native"
  engine: "SPARK"
  connectionRef: "{{connectionRef}}"

  audit:
    sink:
      connectionRef: "{{connectionRef}}"

  connections:
    localFileSystem:
      type: "fs" # Connection to local file system (delta files)
    starbake-bigquery:
      type: "bigquery"
      options:
        location: europe-west1
        authType: "APPLICATION_DEFAULT"
        authScopes: "https://www.googleapis.com/auth/cloud-platform"
        writeMethod: "direct"

  defaultWriteFormat: "parquet" # "parquet" (default) or "delta"

  dagRef:
    load: "dagster_load_shell"
    transform: "dagster_transform_shell"
