---
application:
  loader: "native" # "spark" (default) or "native"
  connectionRef: "{{connectionRef}}"

  audit:
    sink:
      connectionRef: "{{connectionRef}}"

  connections:
    starbake-bigquery:
      type: "bigquery"
      options:
        location: europe-west1
        authType: "APPLICATION_DEFAULT"
        authScopes: "https://www.googleapis.com/auth/cloud-platform"
        writeMethod: "direct"
    FS:
      type: local

  dagRef:
    load: "load"
    transform: "transform"
