---
version: 1
load:
  name: "sales_kpi"
  metadata:
    format: "DSV"
    encoding: "UTF-8"
    multiline: false
    array: false
    withHeader: true
    separator: ";"
    quote: "\""
    escape: "\\"
    sink: {}
    emptyIsNull: true
  database: "starlake-325712"
