connections:
  bigquery:
    type: "bigquery"
    options:
      gcsBucket: "starlake-app"
      authType: APPLICATION_DEFAULT
      #authType: SERVICE_ACCOUNT_JSON_KEYFILE
      #jsonKeyfile: "/Users/me/.gcloud/keys/me.json"
  filesystem:
    type: "fs"



connectionRef: {{ myConnectionRef }}



validator: "spark" # native of spark

spark:
  datasource:
    bigquery:
      materializationDataset: {{ bigQueryMaterializationDataset }}
