application:
  connections:
    bigquery:
      type: "bigquery"
      options:
        gcsBucket: "starlake-app"
        authType: APPLICATION_DEFAULT
        #authType: SERVICE_ACCOUNT_JSON_KEYFILE
        #jsonKeyfile: "/Users/hayssams/.gcloud/keys/starlake-hayssams.json"
    localFilesystem:
      type: "fs"

  # default connection
  connectionRef: "{{ myConnectionRef }}"

  validator: "spark" # native of spark
  spark:
    datasource:
      bigquery:
        materializationDataset: {{ bigQueryMaterializationDataset }}

