---
version: 1
table:
  name: "products"
  pattern: "products.*.json"
  attributes:
  - name: "category"
    type: "string"
    array: false
    sample: "bread"
  - name: "cost"
    type: "double"
    array: false
    sample: "8.12"
  - name: "description"
    type: "string"
    array: false
    sample: "This delicious Baguette is made with the finest ingredients and baked\
      \ to perfection."
  - name: "name"
    type: "string"
    array: false
    sample: "Baguette"
  - name: "price"
    type: "double"
    array: false
    sample: "14.33"
  - name: "product_id"
    type: "int"
    array: false
    sample: "1"
  metadata:
    format: "JSON_FLAT"
    withHeader: true
    writeStrategy:
      type: "APPEND"
  comment: "This table contains information about various Starbake products."
  sample: "{\"category\":\"bread\",\"cost\":8.12,\"description\":\"This delicious\
    \ Baguette is made with the finest ingredients and baked to perfection.\",\"name\"\
    :\"Baguette\",\"price\":14.33,\"product_id\":1}\n{\"category\":\"pastry\",\"cost\"\
    :1.75,\"description\":\"A flaky, buttery croissant filled with rich chocolate.\"\
    ,\"name\":\"Chocolate Croissant\",\"price\":3.99,\"product_id\":2}\n{\"category\"\
    :\"bread\",\"cost\":3.25,\"description\":\"Artisanal sourdough bread with a crispy\
    \ crust and tangy flavor.\",\"name\":\"Sourdough Loaf\",\"price\":6.5,\"product_id\"\
    :3}\n{\"category\":\"pastry\",\"cost\":1.2,\"description\":\"Moist muffin packed\
    \ with juicy blueberries and topped with a crumbly streusel.\",\"name\":\"Blueberry\
    \ Muffin\",\"price\":2.75,\"product_id\":4}\n{\"category\":\"pastry\",\"cost\"\
    :1.8,\"description\":\"Soft, gooey cinnamon roll with a generous drizzle of cream\
    \ cheese frosting.\",\"name\":\"Cinnamon Roll\",\"price\":3.5,\"product_id\":5}\n\
    {\"category\":\"bread\",\"cost\":2.75,\"description\":\"Nutritious whole grain\
    \ bread packed with seeds and nuts.\",\"name\":\"Whole Grain Bread\",\"price\"\
    :5.25,\"product_id\":6}\n{\"category\":\"pastry\",\"cost\":1.5,\"description\"\
    :\"Flaky pastry filled with cinnamon-spiced apples and drizzled with vanilla glaze.\"\
    ,\"name\":\"Apple Turnover\",\"price\":3.25,\"product_id\":7}\n{\"category\":\"\
    bread\",\"cost\":2.25,\"description\":\"Italian flatbread topped with olive oil,\
    \ herbs, and sea salt.\",\"name\":\"Focaccia\",\"price\":4.75,\"product_id\":8}\n\
    {\"category\":\"pastry\",\"cost\":1.85,\"description\":\"Buttery Danish pastry\
    \ filled with sweet raspberry jam and topped with almond slivers.\",\"name\":\"\
    Raspberry Danish\",\"price\":3.75,\"product_id\":9}\n{\"category\":\"bread\",\"\
    cost\":2.8,\"description\":\"Dense and flavorful rye bread, perfect for sandwiches\
    \ or toasting.\",\"name\":\"Rye Bread\",\"price\":5.5,\"product_id\":10}\n{\"\
    category\":\"cookie\",\"cost\":0.75,\"description\":\"Classic chocolate chip cookie\
    \ with a soft center and crispy edges.\",\"name\":\"Chocolate Chip Cookie\",\"\
    price\":1.5,\"product_id\":11}\n{\"category\":\"pastry\",\"cost\":1.4,\"description\"\
    :\"Savory scone packed with cheddar cheese and a hint of herbs.\",\"name\":\"\
    Cheese Scone\",\"price\":2.95,\"product_id\":12}\n{\"category\":\"bread\",\"cost\"\
    :2.1,\"description\":\"Moist banana bread made with ripe bananas and a touch of\
    \ cinnamon.\",\"name\":\"Banana Bread\",\"price\":4.25,\"product_id\":13}\n{\"\
    category\":\"pastry\",\"cost\":2.2,\"description\":\"Buttery croissant filled\
    \ with almond cream and topped with sliced almonds.\",\"name\":\"Almond Croissant\"\
    ,\"price\":4.5,\"product_id\":14}\n{\"category\":\"bread\",\"cost\":3.0,\"description\"\
    :\"Dark, dense pumpernickel bread with a rich, complex flavor.\",\"name\":\"Pumpernickel\
    \ Bread\",\"price\":5.75,\"product_id\":15}\n{\"category\":\"pastry\",\"cost\"\
    :2.5,\"description\":\"Tangy lemon curd in a buttery shortcrust pastry shell.\"\
    ,\"name\":\"Lemon Tart\",\"price\":4.95,\"product_id\":16}\n{\"category\":\"cookie\"\
    ,\"cost\":0.85,\"description\":\"Chewy oatmeal cookie packed with plump raisins\
    \ and a hint of cinnamon.\",\"name\":\"Oatmeal Raisin Cookie\",\"price\":1.75,\"\
    product_id\":17}\n{\"category\":\"bread\",\"cost\":3.5,\"description\":\"Rich,\
    \ buttery brioche bread with a tender crumb and golden crust.\",\"name\":\"Brioche\"\
    ,\"price\":6.25,\"product_id\":18}\n{\"category\":\"pie\",\"cost\":9.5,\"description\"\
    :\"Classic pecan pie with a gooey filling and crunchy pecan topping.\",\"name\"\
    :\"Pecan Pie\",\"price\":18.99,\"product_id\":19}\n{\"category\":\"bread\",\"\
    cost\":1.95,\"description\":\"Crusty bread infused with garlic butter and herbs,\
    \ ready to be warmed.\",\"name\":\"Garlic Bread\",\"price\":3.99,\"product_id\"\
    :20}"
