---
version: 1
load:
  name: "all_inclusive"
  metadata:
    format: "DSV"
    encoding: "ISO-8859-1"
    multiline: false
    array: false
    withHeader: true
    separator: ";"
    quote: "\""
    escape: "\""
    writeStrategy:
      types:
        OVERWRITE: 'group("mode") == "T" || group("mode") == ""'
        APPEND: 'group("mode") == "D"'
        DELETE_THEN_INSERT: 'group("mode") == "A"'
  rename: "target_all_inclusive"
  database: "{{project_id}}"