---
version: 1
table:
  name: "product"
  pattern: "product.*.xml"
  attributes:
  - name: "category"
    type: "string"
    array: false
    required: false
    privacy: "NONE"
    ignore: false
  - name: "cost"
    type: "double"
    array: false
    required: false
    privacy: "NONE"
    ignore: false
  - name: "description"
    type: "string"
    array: false
    required: false
    privacy: "NONE"
    ignore: false
  - name: "name"
    type: "string"
    array: false
    required: false
    privacy: "NONE"
    ignore: false
  - name: "price"
    type: "double"
    array: false
    required: false
    privacy: "NONE"
    ignore: false
  - name: "product_id"
    type: "long"
    array: false
    required: false
    privacy: "NONE"
    ignore: false
  metadata:
    format: "XML"
    encoding: "UTF-8"
    multiline: false
    array: false
    withHeader: true
    separator: ";"
    quote: "\""
    escape: "\\"
    options:
      rowTag: "record"
    emptyIsNull: true
    writeStrategy:
      type: "OVERWRITE"
