audit:
  sink:
    connectionRef: {{ connection_ref }}


accessPolicies:
  apply: true
  location: EU


#connectionRef: {{ connection_ref }}
spark:
  datasource:
    bigquery:
      allowFieldAddition: "true"
      allowFieldRelaxation: "true"

connections:
  bigquery:
    type: "bigquery"
    options:
      gcsBucket: "starlake-app"
      authType: "APPLICATION_DEFAULT"
      #authType: SERVICE_ACCOUNT_JSON_KEYFILE
      #jsonKeyfile: "/Users/hayssams/.gcloud/keys/starlake-hayssams.json"

  sparkLocal:
    type: "fs"


# validator: "spark" # "spark" or "native"
connectionRef: {{ connection_ref }}
