name: Release
# Run workflow on commits to the `master` branch
on:
  workflow_dispatch:
env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        if: ${{ !github.event.repository.fork }}
        with:
          java-version: 1.8
      - name: Release Spark 2/3
        run: sbt 'release with-defaults'
